#!/usr/bin/env python3
import argparse,json,re,sys,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
CAT=json.loads((ROOT/'contracts/catalog.json').read_text())
OUT=ROOT/'sdk/go/generated'

def pkg_name(ident):
 base,major=ident.rsplit('@',1); return re.sub(r'[^a-zA-Z0-9]','',base).lower()+'v'+major

def go_name(s):
 parts=re.split(r'[^A-Za-z0-9]+',s); special={'id':'ID','ids':'IDs','url':'URL','uri':'URI','api':'API','cpu':'CPU','sha256':'SHA256','ms':'MS'}
 return ''.join(special.get(x.lower(),x[:1].upper()+x[1:]) for x in parts if x) or 'Value'

UNSUPPORTED_CODEGEN_KEYS={"$ref","$defs","definitions","oneOf","anyOf","allOf","not","if","then","else","dependentSchemas","prefixItems","contains","unevaluatedProperties","unevaluatedItems"}

def validate_codegen_schema(schema,path='$'):
 if not isinstance(schema,dict): raise ValueError(f'{path}: schema must be an object')
 bad=UNSUPPORTED_CODEGEN_KEYS.intersection(schema)
 if bad: raise ValueError(f'{path}: unsupported codegen keywords {sorted(bad)}')
 t=schema.get('type')
 if isinstance(t,list):
  nonnull=[x for x in t if x!='null']
  if len(nonnull)!=1: raise ValueError(f'{path}: only one non-null union member is supported')
  t=nonnull[0]
 if t not in (None,'string','integer','number','boolean','array','object'):
  raise ValueError(f'{path}: unsupported type {t!r}')
 if t=='array' or 'items' in schema:
  if not isinstance(schema.get('items'),dict): raise ValueError(f'{path}: array items schema required')
  validate_codegen_schema(schema['items'],path+'[]')
 if t=='object' or 'properties' in schema:
  ap=schema.get('additionalProperties',True)
  if not isinstance(ap,bool): raise ValueError(f'{path}: schema-valued additionalProperties not supported by Go generator')
  for k,v in schema.get('properties',{}).items(): validate_codegen_schema(v,path+'.'+k)

def type_for(schema,name,decls):
 if not schema: return 'json.RawMessage'
 t=schema.get('type')
 if isinstance(t,list):
  nonnull=[x for x in t if x!='null']; t=nonnull[0] if len(nonnull)==1 else None
 if t=='string': return 'string'
 if t=='integer': return 'int'
 if t=='number': return 'float64'
 if t=='boolean': return 'bool'
 if t=='array': return '[]'+type_for(schema.get('items',{}),name+'Item',decls)
 if t=='object' or 'properties' in schema:
  props=schema.get('properties',{})
  if not props:
   return 'struct{}' if schema.get('additionalProperties',True) is False else 'map[string]any'
  typename=name
  if typename not in decls:
   decls[typename]=None
   lines=[f'type {typename} struct {{']
   req=set(schema.get('required',[]))
   for k,v in props.items():
    gt=type_for(v,typename+go_name(k),decls)
    tag=k if k in req else k+',omitempty'
    lines.append(f'\t{go_name(k)} {gt} `json:"{tag}"`')
   lines.append('}')
   decls[typename]='\n'.join(lines)
  return typename
 return 'json.RawMessage'

def render(ident,schema):
 validate_codegen_schema(schema['request'],'request'); validate_codegen_schema(schema['response'],'response')
 decls={}
 req=type_for(schema['request'],'Request',decls); resp=type_for(schema['response'],'Response',decls)
 # type_for creates Request/Response declarations in decls
 imports='import "encoding/json"\n\n' if any('json.RawMessage' in (v or '') for v in decls.values()) else ''
 ordered=[]
 # nested declarations may be inserted before parents; any order is valid in Go.
 for _,v in decls.items():
  if v: ordered.append(v)
 major=int(ident.rsplit('@',1)[1]); kind=schema.get('kind','')
 consts=f'const Contract = "{ident}"\nconst Major = {major}\nconst Kind = "{kind}"\n\n'
 text=f'// Code generated by tools/generate_contracts.py; DO NOT EDIT.\npackage {pkg_name(ident)}\n\n{imports}{consts}'+'\n\n'.join(ordered)+'\n'
 p=subprocess.run(['gofmt'],input=text,text=True,capture_output=True)
 if p.returncode: raise RuntimeError(p.stderr)
 return p.stdout

def generate(check=False):
 mismatches=[]
 for ident,rel in sorted(CAT.items()):
  schema=json.loads((ROOT/'contracts'/rel).read_text()); text=render(ident,schema)
  d=OUT/pkg_name(ident); p=d/'types.gen.go'
  if check:
   if not p.exists() or p.read_text()!=text: mismatches.append(str(p.relative_to(ROOT)))
  else:
   d.mkdir(parents=True,exist_ok=True);p.write_text(text)
 if check and mismatches:
  print('GENERATED CONTRACT SDK OUT OF DATE');[print(' -',x) for x in mismatches];return 1
 print('GENERATED CONTRACT SDK: '+('UP TO DATE' if check else 'UPDATED')+f' ({len(CAT)} contracts)');return 0
if __name__=='__main__':
 ap=argparse.ArgumentParser();ap.add_argument('--check',action='store_true');a=ap.parse_args();sys.exit(generate(a.check))
